# Generated by Django 5.1.1 on 2024-09-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
