# Generated by Django 5.1.1 on 2024-10-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnose',
            name='detail',
        ),
        migrations.AddField(
            model_name='diagnose',
            name='details',
            field=models.JSONField(default=dict),
        ),
    ]
