name: CI/CD Pipeline for Potadi Server Django

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      # Step 3: Deploy to server
      - name: Deploy to server
        run: |
            ssh user@server "cd /home/lppm/APPS/potadiapp-backend && git pull && docker-compose down && docker-compose up -d --build && docker network connect tunnel backend"
