name: CI/CD Pipeline for Potadi Server Django

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Pull the latest changes
      - name: Git Pull Latest Changes
        run: git pull origin master

      # Step 5: Bring down any existing containers
      - name: Stop and remove old containers
        run: docker-compose down

      # Step 6: Build and start new containers
      - name: Build and start containers
        run: docker-compose up -d --build

      # Step 7: Connect to tunnel network
      - name: Connect container to network tunnel
        run: docker network connect tunnel backend